language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: Ku/6tvQIDsibfImCSrDj5lLCFm3UuanAmJ4TfSzErwud21jEwNgpk4LA3WqWX6Qwk7IOT4JEo4cgu8EW/qKaIIrTeaQTM1/92kLrKoLdApa6Ai4hsJnhtfgZvyVnKmfm3w7+KEmHJE7VNuUp/srMUU4ckR2J8GwEbf8EpPa22nVAJEa+C9i46sPVDQigeQloontnqhqtfLhm4mv7BUML+rDPHGDlJnATfXjyDlYqynlLnLkam6NpiupKW9F3Y5MY43sjGiaPQIRQ5aBQ6wSz0nVEnOGXhAXSuA5guw9bFulaEVSTGbOvaeKYnXI6/72jb15vv75satwt11C1cZuSYKmlt0CTQHyhLTiLaJwQGhGy0LmA0MF/Mw9nht/V8f4ldAT35/zwe+1+J9ig06zJ5+fko5xVQkyQhvcs8miU3xeHXQCqEVefhiwEFsgkUM4tEtCfSmdwPKs16v3zhplPyhfHvNMl+mnh9k3h6ZdrlGOLvQWKr8YjSL3Z6XUqTt9rRR1QpF6mG6D01nxFz47grlilodV13+COs2XvwttDEMiUeQIURDxU+QsQIV86JGRjoy0eJDV7xaxKCKyGJY0ewGXOcUrZJJlc51hRhDj6bKAUhTYH1YkQgmH/dsLRV/wtlPAynp40izLa5ImPe2qJpaOks2VnZTOsUz1WOUH6wQw=
  - secure: oTn8Zl2uxI5qjGjJYv32Pgdg/WTPnNw6/XjrzSZ7Ukx6JJRmfEqDbpdWnkWvn3cxSHXbESgcezO6dkhMFFQV3PegANMvlX/FIDJtAfSiUApNarbdQpIA5zGp1jzOIr7hk/cKjUwUhz1cELCyeeDpuby9MoTsw4wUdldj+D7LAM06YXdvPW3aK8ejf49cinlE//LFbf8ib7T7tZAlvevQzt80SpeGbCKj7IJfkb9vHb81hiMo3YitJ6wdayQXn4UJYzRaPwDWoDAXMsd3s5wuAtV0URSmYTWT0O/0nTpy+Ec2ygtsp9HEwXIRcSvZmy3k7dgxPAy/o3RMsY8yRKbSeZmT735U2uHrGWGVxUIunbWTQHUTZ8hkgbP4lKyR6qRsMpw7gPMd8weMc/G/uXmQ2eWfS5i046ksZxE8utUBkrOf3gJ39TZnyOWa+FOvuODSSyG/Clv/GWSzrlNEP+238HxNSLeU1IE/ZWK73JonJdSao17TgZ/rmvvBkYCaJQO8G0+RH1ulMx4QDhltbFmCHS8IeSp/7+GZgGWazCk76kqiNdtofj44/+Bl+IzBaBQVASrjPZhbXF0aTnV5Irl7HmvtOPA2h1Aj89cfmtVe40izCk7i52VyJLUgAWYKGRKzmOhoGP64GDV/Jj3hu99B8U6buuBaSLfVw0G0tEH+IRE=
